### ISSUE TITLE
http to https

### ISSUE THREAD

**Issue by GuillaumeRossolini** [spatie/checklist-going-live#10]
The first item of your checklist (replace http with https) can be skipped when the following is in place: 
- permanent http to https redirect of the whole domain;
- Let's Encrypt tends to configure the HSTS header for returning visitors;
- also configure the upgrade-insecure-requests CSP header, at least for the first visit; 
- if you really want this replacement to happen in the HTML sent to the browser,  you can add an output filter in whichever server software you are using.

This way, your codebase is still compatible with dev boxes, you just need to override the DNS with hosts file

**Comment by sebastiandedeyne** [comment]
We install Let's Encrypt through Laravel Forge. This makes it very easy for us to manage, but doesn't allow us to do advances things and can be activated when the domain has gone live, which is why we do it like this. We don't really mind this because it's all so simple this way, the extra step when going live (which only happens once anyway) isn't worth the added of maintaining Let's Encrypt ourselves.

Regarding the html replacement, Laravel takes care of that with an env variable that contains the app's URL.
